title: iconmaster.info
email: iconmaster@csh.rit.edu
author: Joshua Robbins
description: >
  This is the blog for Joshua Robbins, aka Iconmaster.
  I post about my new projects, my insights into computer science, and probably stuff about video games, too.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iconmaster.info"
twitter_username: iconmaster5326
github_username:  iconmaster5326

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: iconmaster
  
excerpt_separator: <!--readmore-->