title: iconmaster.info
email: iconmaster@csh.rit.edu
author: Joshua Robbins
description: >
  A Dragon's Musings

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iconmaster.info"
twitter_username: iconmaster5326
github_username:  iconmaster5326

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: iconmaster
  
excerpt_separator: <!--readmore-->